# -*- coding: utf-8 -*-
"""Data Science Titanic Case - Elsa Riesta Alika

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3ePWmugIqYs0p_0PNSZQ22TO0NJ9ozx

## Investigasi sampel data titanic berikut dengan cara :
1. Cek secara head, tail, sample, info lalu observasi apa yang bisa anda peroleh ?
2. Lakukan Statistical Summary dengan mengekstrak informasi yang didapat dari observasi anda ?
3. Cek apakah ada duplikat dan bagaimana handlenya ?
4. Cek apakah ada missing value, berapa persentasenya jika ada, dan bagaimana cara handlenya ?

## Import Libraries
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
from sklearn.preprocessing import LabelEncoder, StandardScaler

# import data
df = pd.read_excel('titanic.xlsx')
df.head()

df.tail()

df.sample(5)

"""Observation:


1. All columns except "age" are categorical.

2. The "survived" variable is binary (0,1).

3. The "sex" variable contains distinct values: "female" and "male".

4. There appears a variable with missing values, particularly in 'age'. This issue will be handle next

4. There are no significant issues found in the data (column names match the entries).



"""

df.info()

"""1. The data contains 4 columns with 500 rows.  
2. Only the **"age"** variable has missing values, which will be processed further.  
3. The **"age"** data contains float values, and values below 1 will be considered as observations with an age of less than 1 year. Need a comfirmation from the source of dataset
4. Otherwise, the data appears to align with the column names.

#Statistical Summary
"""

df.columns

categoric = ['name', 'sex']
numeric = ['survived','age']

df[numeric].describe()

"""1. Overall, the minimum and maximum values seem reasonable for this variable.  
2. The **"age"** variable has a minimum value of 0.6, which can be considered as an age of less than 1 year.  
3. The mean is approximately 50% (Median), indicating that the variable is close to a normal distribution.  
4. The **"survived"** variable is binary (0 and 1), so there is no need to conclude its symmetry. It only needs to be checked for balance.
"""

df[categoric].describe()

"""1. Both name and **sex** columns have 500 entries with no missing values.

2. There are 499 unique names, indicating one duplicate entry: "Eustis, Miss. Elizabeth Mussey", which suggests a potential duplicate that may need further checking.

3. The dataset contains 288 males and 212 females, showing that males are more represented.
"""

#untuk mengetahui berapa banyak gender dan status survived dengan detail
print(df['sex'].value_counts(), '\n')
print(df['survived'].value_counts())

"""

1.   For gender, it is true that "male" appears in more rows than "female".
2.   It shows that most passengers survived, with 270 survivors, while the rest did not.

"""

print(df['age'].value_counts())

"""The **"age"** variable shows that the most common age is 24 years, with 23 passengers, followed by 30 years, with 20 passengers.

#Cleaning Data

##Handling Duplicate
"""

len(df.drop_duplicates())/len(df)
#Hasil menunjukkan bahwa benar terdapat baris yang duplicate

duplicates = df[df.duplicated(keep=False)]
duplicates
#Asumsi seelumnya benar, ada duplicate data pada baris 104 dan baris 349

#Handling Drop duplicate
data = df.drop_duplicates()
len(data.drop_duplicates())/len(data)

#====== Handling Duplicate Data Finish ==============

"""Handling data duplicate telah dilakukan

#Handling Missing Value
"""

data.isna().sum()

total_rows = len(data)

# Menghitung dan menampilkan persentase missing values di setiap kolom satu per satu
for column in data.columns:
    missing_count = data[column].isna().sum()
    missing_percentage = (missing_count / total_rows) * 100
    print(f"Column '{column}' Has {missing_count} missing values ({missing_percentage:.2f}%)")

"""Terdapat 49 data missing value pada variabel **age**. Variabel lainnya telah lengkap.

Persentase missing value adalah 9.82% yang dimana berada dibawah 20%. Oleh karena itu, missing value ini dapat kita handling dengan **Median Imputation**, hal ini karena data **age** adalah data numerik
"""

# Visualisasi distribusi umur
plt.figure(figsize=(8, 4))
sns.histplot(data['age'], kde=True, bins=30, color='skyblue')
plt.title('Distribusi Umur Penumpang Titanic')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Menghitung nilai skewness
skew_value = data['age'].skew()
print(f"Skewness: {skew_value:.2f}")

data[column].fillna(data[column].mean(), inplace=True)

data.isna().sum()

data.info()

"""**Duplicate** dan** Missing Values** pada data telah berhasil diselesaikan. Pada hasil akhir menunjukkan bahwa data yang bisa digunakan terdapat **499** baris **tanpa adanya missing value**."""

# Visualisasi distribusi umur
plt.figure(figsize=(8, 4))
sns.histplot(data['age'], kde=True, bins=30, color='skyblue')
plt.title('Distribusi Umur Penumpang Titanic')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Menghitung nilai skewness
skew_value = data['age'].skew()
print(f"Skewness: {skew_value:.2f}")

"""# Visualisasi EDA"""

# Plot gender vs survived
sns.countplot(data=data, x='sex', hue='survived')
plt.title('Gender vs Survived')
plt.show()

# Plot age distribution after imputation
sns.histplot(data['age'], kde=True)
plt.title('Age Distribution')
plt.show()

"""#Analisis Survival Rate

"""

# Menghitung survival rate per gender
survival_by_gender = data.groupby('sex')['survived'].mean().reset_index()
survival_by_gender

# Hitung jumlah yang selamat berdasarkan gender
survived_counts = data[data['survived'] == 1]['sex'].value_counts()

# Pie chart
plt.figure(figsize=(6,6))
plt.pie(survived_counts, labels=survived_counts.index, autopct='%1.1f%%', startangle=90, colors=['#f6c1c1', '#8fd9b6'])
plt.title('Proporsi Penumpang Selamat Berdasarkan Gender')
plt.axis('equal')  # Biar pie-nya bulat
plt.show()

# Visualisasi distribusi usia penumpang
plt.figure(figsize=(8,6))
sns.histplot(data['age'], kde=True, bins=30, color='skyblue')
plt.title('Distribusi Usia Penumpang Titanic')
plt.xlabel('Usia')
plt.ylabel('Jumlah Penumpang')
plt.show()

# Membuat kategori usia dengan 4 kelompok
def age_group(age):
    if age < 13:
        return 'Children'
    elif age < 20:
        return 'Teenager'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'
data['age_group'] = data['age'].apply(age_group)

# Hitung survival rate berdasarkan kategori umur
survival_by_age_group = data.groupby('age_group')['survived'].mean().reset_index()

order = ['Children', 'Teenager', 'Adult', 'Senior']

plt.figure(figsize=(6, 4))
ax = sns.barplot(data=survival_by_age_group, x='age_group', y='survived', order=order, palette='viridis')

for p in ax.patches:
    ax.annotate(f'{p.get_height():.2f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=10, color='black')

plt.title('Survival Rate by Age Group')
plt.ylabel('Survival Rate')
plt.ylim(0, 1)
plt.show()

# Gabungan analisis gender dan age group
grouped = data.groupby(['sex', 'age_group'])['survived'].mean().reset_index()

plt.figure(figsize=(8,5))
ax = sns.barplot(data=grouped, x='age_group', y='survived', hue='sex', palette='pastel')

for p in ax.patches:
    height = p.get_height()
    ax.annotate(f'{height:.2f}',
                (p.get_x() + p.get_width() / 2., height + 0.02),
                ha='center', va='bottom', fontsize=9, color='black')

plt.title('Survival Rate by Age Group and Gender')
plt.ylabel('Survival Rate')
plt.ylim(0, 1.4)
plt.show()

"""# Feature Engineering"""

data.sample(5)

data_cleaned = data.drop(['name',"age_group"], axis=1)
data_cleaned.head()

le = LabelEncoder()
data_cleaned['sex'] = le.fit_transform(data_cleaned['sex'])  # Males = 1, Females = 0

data_cleaned.head()

# Menampilkan nama kolom dalam dataset
print(data_cleaned.columns)

"""# Feature Importance Modelling"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

X = data_cleaned.drop(['survived'], axis=1)
y = data_cleaned['survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Decision Tree
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Visualisasi Pohon Keputusan
plt.figure(figsize=(15,10))
tree.plot_tree(model, filled=True, feature_names=X_train.columns, class_names=['Died', 'Survived'], rounded=True)
plt.show()

# Menampilkan Fitur yang Paling Berpengaruh
feature_importance = pd.DataFrame(model.feature_importances_, index=X_train.columns, columns=['Importance']).sort_values('Importance', ascending=False)

# Output
plt.figure(figsize=(10,6))
feature_importance.plot(kind='barh', legend=False)
plt.title('Feature Importance')
plt.xlabel('Importance')
plt.ylabel('Features')
plt.show()

# Menampilkan data feature importance
feature_importance.head()